transaction_service/index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.main_page, name='main_page')
]

transaction_service/transaction_service/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('transactions/',
         include('transactions.urls', namespace='transactions')),
    path('', include('index.urls', namespace='index')),
]

transaction_service/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('sign_up/', views.SignUp.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html'),
         name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm')
]

transaction_service/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-2 mt-5">
    <p>
        © 2022 Copyright
        <a href="https://github.com/deorz" style="color: rebeccapurple">
            deorz<img src="{% static 'img/github.svg' %}"
                     class="d-inline-block align-top">
        </a>
    </p>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>


    {{ form.media }}

    <script>
        (function ($) {
            $('#add-form').click(function () {
                var index = $('#id_inline_test_models-TOTAL_FORMS').val()
                var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
                newTable.find(':input').each(function () {
                    for (attr of ['name', 'id'])
                        $(this).attr(
                            attr,
                            $(this).attr(attr).replace('__prefix__', index)
                        )
                })
                newTable.insertBefore($(this))
                $('#id_inline_test_models-TOTAL_FORMS').val(
                    parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
                )
                newTable.slideDown()
            })
        })($)
    </script>
</footer>

transaction_service/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-dark"
         style="background-color: #5957f9;">
        <div class="container">
            <a class="navbar-brand" style="margin-left: 0px"
               href="{% url 'index:main_page' %}">
                <img src="{% static 'img/credit-card.svg' %}"
                     class="d-inline-block align-top">
                Transaction<span
                    style="color: black">Service</span>
            </a>
            <ul class="nav nav-pills">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link link-dark"
                           href="{% url 'users:profile' %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-dark"
                           href="{% url 'users:password_change' %}">Изменение
                            пароля</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-dark"
                           href="{% url 'users:logout' %}">
                            Выход
                        </a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-dark"
                           href="{% url 'users:login' %}">
                            Войти
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-dark"
                           href="{% url 'users:sign_up' %}">
                            Зарегистрироваться
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

transaction_service/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" style="color: black; border-color: rebeccapurple" href="?page={{ page_obj.previous_page_number }}">
                        &laquo;
                    </a>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item disabled">
                        <span class="page-link" style="color: black; border-color: rebeccapurple">
                            {{ i }}
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" style="color: black; border-color: rebeccapurple" href="?page={{ i }}">
                            {{ i }}
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" style="color: black; border-color: rebeccapurple" href="?page={{ page_obj.next_page_number }}">
                        &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}