transaction_service/index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.main_page, name='main_page')
]

transaction_service/transaction_service/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('transactions/',
         include('transactions.urls', namespace='transactions')),
    path('', include('index.urls', namespace='index')),
]

transaction_service/transactions/urls.py
from django.urls import path
from django.urls import re_path as url

from . import views

from .models import Wallet

app_name = 'transactions'

urlpatterns = [
    path('create_transaction/', views.CreateTransactionView.as_view(),
         name='create_transaction'),
    path('create_wallet/', views.CreateWalletView.as_view(),
         name='create_wallet'),
    path('wallet_list/', views.WalletListView.as_view(),
         name='wallet_list'),
    path('transaction_history/', views.TransactionHistoryView.as_view(),
         name='transaction_history'),
    path('transaction_history/order_by/<str:order_by>/',
         views.TransactionHistoryView.as_view(),
         name='transaction_history_ordered'),
    path('transaction_history/sort_by/<str:name>/',
         views.TransactionHistoryView.as_view(),
         name='transaction_history_sorted'),
    path('transaction/<int:pk>/', views.TransactionDetailView.as_view(),
         name='transaction_detail'),
    path('wallet/<uuid:pk>/', views.WalletDetailView.as_view(),
         name='wallet_detail'),
    url('wallet-autocomplete/',
        views.WalletsAutocomplete.as_view(),
        name='wallet-autocomplete'),
]

transaction_service/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('sign_up/', views.SignUp.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html'),
         name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm')
]

transaction_service/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    first_name = models.CharField(_("first name"), max_length=150,
                                  blank=False)
    last_name = models.CharField(_("last name"), max_length=150,
                                 blank=False)
    email = models.EmailField(_("email address"), blank=False,
                              unique=True)

transaction_service/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'email')

transaction_service/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy

from transactions.models import Wallet, Transaction
from .forms import UserRegisterForm


class SignUp(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/sign_up.html'


class Profile(LoginRequiredMixin, ListView):
    template_name = 'users/profile.html'

    def get_queryset(self):
        return Transaction.objects.filter(
            Q(sender=self.request.user) |
            Q(recipient=self.request.user)
        )[:5]

    def get_context_data(self, **kwargs):
        kwargs.setdefault('money_rest', self.get_money_rest)
        return super().get_context_data(**kwargs)

    def get_money_rest(self):
        user = self.request.user
        wallets = Wallet.objects.filter(user=user)
        money_rest = 0
        for wallet in wallets:
            money_rest += wallet.money_rest
        return money_rest

transaction_service/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
    Войти
{% endblock title %}

{% block content %}
    {% load userfilters %}
    <div class="container mt-4 justify-content-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group mb-0">
                    <div class="card p-4">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <h1>Войти</h1>
                                <p class="text-muted">
                                    Войдите в свой аккаунт
                                </p>
                                {{ form.non_field_errors }}
                                <div class="input-group mb-3">
                                    {{ form.username.errors }}
                                    <span class="input-group-addon"><i
                                            class="fa fa-user"></i></span>
                                    {{ form.username|addattrs:'form-control, Логин' }}
                                </div>
                                <div class="input-group mb-4">
                                    {{ form.password.errors }}
                                    <span class="input-group-addon"><i
                                            class="fa fa-lock"></i></span>
                                    {{ form.password|addattrs:'form-control, Пароль' }}
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit"
                                                class="btn btn-outline-dark px-4">
                                            Войти
                                        </button>
                                    </div>
                                    <div class="col-6 text-right">
                                        <a class="btn btn-link px-0" href="{% url 'users:password_reset' %}">
                                            Забыли пароль?
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card text-white py-5 d-md-down-none"
                         style="width:44%; background-color: #5957f9">
                        <div class="card-body text-center">
                            <div>
                                <h2>Зарегистрироваться</h2>
                                <p>Ещё нет аккаунта в TransactionService?
                                    Регистрация займёт всего пару
                                    секунд...</p>
                                <a class="btn btn-outline-dark mt-3"
                                   href="{% url 'users:sign_up' %}">
                                    Зарегистрироваться!
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/logout.html
{% extends 'base.html' %}
{% block title %}
    Выход
{% endblock title %}

{% block content %}
    <div class="container py-4">
        <h2 class="text-start">Вы успешно вышли из аккаунта.</h2>
        <a class="btn btn-outline-dark" href="{% url 'index:main_page' %}">
            На главную
        </a>
    </div>
{% endblock content %}

transaction_service/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}
    Пароль изменён
{% endblock title %}
{% block content %}
    <div class="container py-4 mt-4">
        <div class="card w-100">
            <h2 class="text-start">Пароль успешно изменён.</h2>
            <div class="justify-content-start">
                <a class="btn btn-outline-dark"
                   href="{% url 'index:main_page' %}">
                    На главную
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}
    Изменение пароля
{% endblock title %}
{% block content %}
    {% load userfilters %}
    <div class="container w- 100 h-100">
        <div class="row h-100">
            <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">Изменение пароля</h1>
                    </div>
                    <div class="card w-100">
                        <div class="card-body">
                            <div class="m-sm-4">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    {% for field in form %}
                                    <div class="form-group">
                                        {{ field.errors }}
                                        <label id="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field|addclass:'form-control form-control-lg' }}
                                    </div>
                                    {% endfor %}
                                    <div class="text-center mt-3">
                                        <button type="submit"
                                           class="btn btn-lg btn-outline-dark">Изменить пароль</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}
    Сброс пароля прошёл успешно
{% endblock title %}
{% block content %}
    <div class="container py-4 mt-4">
        <div class="card w-100">
            <h2 class="text-start">Восстановление пароля завершено.</h2>
            <p>
                Ваш пароль был сохранен. Используйте его для входа
            </p>
            <div class="justify-content-start">
                <a class="btn btn-outline-dark"
                   href="{% url 'users:login' %}">
                    Войти
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}
    Новый пароль
{% endblock title %}
{% block content %}
    {% load userfilters %}
    {% if validlink %}
        <div class="container w- 100 h-100">
            <div class="row h-100">
                <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                    <div class="d-table-cell align-middle">
                        <div class="text-center mt-4">
                            <h1 class="h2">Восстановление пароля</h1>
                            <p class="lead">
                                Придумайте новый пароль.
                            </p>
                        </div>
                        <div class="card w-100">
                            <div class="card-body">
                                <div class="m-sm-4">
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}
                                        {% for field in form %}
                                            <div class="form-group">
                                                {{ field.errors }}
                                                <label id="{{ field.id_for_label }}">{{ field.label }}</label>
                                                {{ field|addclass:'form-control form-control-lg' }}
                                            </div>
                                        {% endfor %}
                                        <div class="text-center mt-3">
                                            <button type="submit"
                                                    class="btn btn-lg btn-outline-dark">
                                                Изменить пароль
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container py-4 mt-4">
            <div class="card w-100">
                <h2 class="text-start">Данная ссылка устарела.</h2>
                <p>
                    Это могло произойти, если вы уже заходили на эту
                    страницу.
                </p>
            </div>
        </div>
    {% endif %}
{% endblock content %}

transaction_service/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}
    Сброс пароля прошёл успешно
{% endblock title %}
{% block content %}
    <div class="container py-4 mt-4">
        <div class="card w-100">
            <h2 class="text-start">Письмо отправлено.</h2>
            <p>Проверьте свою почту,
                вам придёт письмо со ссылкой
                для восстановления пароля.
            </p>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}
    Сброс пароля
{% endblock title %}
{% block content %}
    {% load userfilters %}
    <div class="container w- 100 h-100">
        <div class="row h-100">
            <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">Изменение пароля</h1>
                        <p class="lead">
                            Чтобы сбросить старый пароль — введите адрес
                            электронной почты, под которым вы
                            регистрировались
                        </p>
                    </div>
                    <div class="card w-100">
                        <div class="card-body">
                            <div class="m-sm-4">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    {% for field in form %}
                                        <div class="form-group">
                                            {{ field.errors }}
                                            <label id="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {{ field|addclass:'form-control form-control-lg' }}
                                        </div>
                                    {% endfor %}
                                    <div class="text-center mt-3">
                                        <button type="submit"
                                                class="btn btn-lg btn-outline-dark">
                                            Сбросить пароль
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    Профиль пользователя: {{ user.username }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="container justify-content-start mt-4">
                    <div class="card">
                        <div class="top-container">
                            <div class="ml-3">
                                <h5 class="name">{{ user.get_full_name }}</h5>
                                <p class="mail">{{ user.email }}</p>
                            </div>
                        </div>
                        <div class="middle-container d-flex justify-content-between align-items-center mt-3 p-2">
                            <div class="d-flex flex-column text-right mr-2">
                                <span class="current-balance">Текущий баланс</span>
                                <span class="amount">{{ money_rest }} у.е.</span>
                            </div>
                        </div>
                        <div class="beautiful-div mt-4"><a
                                class="beautiful-button btn"
                                href="{% url 'transactions:create_transaction' %}">Новая
                            транзакция</a></div>
                        <div class="beautiful-div mt-4"><a
                                class="beautiful-button btn"
                                href="{% url 'transactions:create_wallet' %}">Создать
                            кошелёк</a></div>
                        <div class="beautiful-div mt-4"><a
                                class="beautiful-button btn"
                                href="{% url 'transactions:transaction_history' %}">История
                            транзакций</a></div>
                        <div class="beautiful-div mt-4"><a
                                class="beautiful-button btn"
                                href="{% url 'transactions:wallet_list' %}">Мои
                            кошельки</a></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container justify-content-start mt-4">
                    <div class="card" style="width: 55rem;">
                    <span class="text-center">Последние транзакции</span>
                        {% for transaction in object_list %}
                            <div class="beautiful-div mt-4">
                                <a class="btn" href="{% url 'transactions:transaction_detail' transaction.id %}">
                                    <p class="text-start">Дата проведения: {{ transaction.date_provided }}</p>
                                    <p class="text-start">Кому: {{ transaction.recipient.get_full_name }}</p>
                                    <p class="text-start">Сумма: {{ transaction.amount_money }} у.е</p>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

transaction_service/templates/users/sign_up.html
{% extends 'base.html' %}
{% block title %}
    Регистрация
{% endblock title %}

{% block content %}
    {% load userfilters %}
    <div class="container w- 100 h-100">
        <div class="row h-100">
            <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">Регистрация</h1>
                        <p class="lead">
                            Начни пользоваться TransactionService уже
                            сейчас!
                        </p>
                    </div>
                    <div class="card w-100">
                        <div class="card-body">
                            <div class="m-sm-4">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    <div class="form-group">
                                        {{ form.first_name.errors }}
                                        <label id="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                                        {{ form.first_name|addattrs:'form-control form-control-lg,Имя' }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.last_name.errors }}
                                        <label id="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                                        {{ form.last_name|addattrs:'form-control form-control-lg,Фамилия' }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.username.errors }}
                                        <label id="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                                        {{ form.username|addattrs:'form-control form-control-lg,Имя пользователя' }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.email.errors }}
                                        <label id="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                                        {{ form.email|addattrs:'form-control form-control-lg,Email' }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.password1.errors }}
                                        <label id="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
                                        {{ form.password1|addattrs:'form-control form-control-lg,Придумайте пароль' }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.password2.errors }}
                                        <label id="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
                                        {{ form.password2|addattrs:'form-control form-control-lg,Подтверждения пароля' }}
                                    </div>
                                    <div class="col-6 text-right">
                                        <a href="{% url 'users:login' %}"
                                                class="btn btn-link px-0">
                                            Уже есть аккаунт?
                                        </a>
                                    </div>
                                    <div class="text-center mt-3">
                                        <button type="submit"
                                           class="btn btn-lg btn-outline-dark">Зарегистрироваться</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}