transaction_service/index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.main_page, name='main_page')
]

transaction_service/transaction_service/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('transactions/',
         include('transactions.urls', namespace='transactions')),
    path('', include('index.urls', namespace='index')),
]

transaction_service/transactions/urls.py
from django.urls import path
from django.urls import re_path as url

from . import views

from .models import Wallet

app_name = 'transactions'

urlpatterns = [
    path('create_transaction/', views.CreateTransactionView.as_view(),
         name='create_transaction'),
    path('create_wallet/', views.CreateWalletView.as_view(),
         name='create_wallet'),
    path('wallet_list/', views.WalletListView.as_view(),
         name='wallet_list'),
    path('transaction_history/', views.TransactionHistoryView.as_view(),
         name='transaction_history'),
    path('transaction_history/order_by/<str:order_by>/',
         views.TransactionHistoryView.as_view(),
         name='transaction_history_ordered'),
    path('transaction_history/sort_by/<str:name>/',
         views.TransactionHistoryView.as_view(),
         name='transaction_history_sorted'),
    path('transaction/<int:pk>/', views.TransactionDetailView.as_view(),
         name='transaction_detail'),
    path('wallet/<uuid:pk>/', views.WalletDetailView.as_view(),
         name='wallet_detail'),
    url('wallet-autocomplete/',
        views.WalletsAutocomplete.as_view(),
        name='wallet-autocomplete'),
]

transaction_service/transactions/models.py
import uuid

from django.db import models

from users.models import CustomUser


class Wallet(models.Model):
    user = models.ForeignKey(
        CustomUser,
        blank=False,
        on_delete=models.CASCADE,
        related_name='wallets'
    )
    name = models.CharField(verbose_name='Имя счёта',
                            max_length=100, )
    money_rest = models.DecimalField(verbose_name='Остаток средств',
                                     max_digits=12,
                                     decimal_places=2,
                                     null=False)
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          unique=True,
                          editable=False,
                          )
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return (f'Имя пользователя: {self.user.username} '
                f'Имя счёта: {self.name}')


class Transaction(models.Model):
    sender = models.ForeignKey(
        CustomUser,
        blank=False,
        on_delete=models.DO_NOTHING,
        related_name='transaction_sender',
        verbose_name='Отправитель'
    )
    recipient = models.ForeignKey(
        CustomUser,
        blank=False,
        on_delete=models.DO_NOTHING,
        related_name='transaction_recipient',
        verbose_name='Получатель'
    )

    recipient_wallet = models.ForeignKey(
        Wallet,
        blank=False,
        on_delete=models.DO_NOTHING,
        related_name='recipient_wallet',
        verbose_name='Кошелёк получателя',
        help_text='Введите имя пользователя или почту получателя'
    )

    amount_money = models.DecimalField(verbose_name='Сумма перевода',
                                       max_digits=12,
                                       decimal_places=2,
                                       blank=False)

    wallets_to_pay = models.ManyToManyField(
        Wallet,
        through='Link',
        verbose_name='Кошельки для оплаты'
    )

    date_provided = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_provided']

    def __str__(self):
        return (f'{self.date_provided.strftime("%H:%M:%S %a %d-%m-%Y")} '
                f'перевод от {self.sender.get_full_name()} к '
                f'{self.recipient.get_full_name()} '
                f'сумма: {self.amount_money} у.е.')


class Link(models.Model):
    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.DO_NOTHING,
        verbose_name='Кошелёк'
    )
    transaction = models.ForeignKey(
        Transaction,
        on_delete=models.CASCADE,
        verbose_name='Транзакция'
    )

    def __str__(self):
        return (f'{self.transaction.id}: {self.transaction.sender} - '
                f'{self.transaction.recipient}')

transaction_service/transactions/forms.py
from dal import autocomplete
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Wallet, Transaction


class TransactionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')

        super().__init__(*args, **kwargs)

        self.fields['wallets_to_pay'] = forms.ModelMultipleChoiceField(
            queryset=Wallet.objects.filter(
                user=self.request.user),
            widget=forms.CheckboxSelectMultiple,
            label='Кошельки для оплаты')

        self.fields[
            'recipient_wallet'].empty_label = 'Пользователь не выбран'

    class Meta:
        model = Transaction
        fields = ('recipient_wallet',
                  'wallets_to_pay',
                  'amount_money')
        widgets = {
            'recipient_wallet': autocomplete.ModelSelect2(
                url='wallet-autocomplete/')
        }

    def clean_amount_money(self):
        amount_money = self.cleaned_data['amount_money']
        if amount_money <= 0:
            raise ValidationError(
                _('Вы не можете перевести эту сумму'))
        return amount_money


class WalletForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Wallet
        fields = ('name',
                  'money_rest')

    def clean_money_rest(self):
        money_rest = self.cleaned_data['money_rest']
        if money_rest < 0:
            raise ValidationError(_(
                'На вашем кошельке не может быть отрицательная сумма'
            ))
        return money_rest

    def clean_name(self):
        name = self.cleaned_data['name']
        user = self.request.user
        names_queryset = Wallet.objects.filter(
            user=user).values('name')
        for names in names_queryset:
            if name == names['name']:
                raise ValidationError(_(
                    'У вас уже есть кошелёк с таким именем'
                ))
        return name

transaction_service/transactions/views.py
from dal import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView, DetailView

from .forms import TransactionForm, WalletForm
from .models import Transaction, Link, Wallet


class WalletsAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Wallet.objects.none()
        queryset = Wallet.objects.all().exclude(user=self.request.user)
        if self.q:
            queryset = queryset.filter(
                Q(user__username__contains=self.q) |
                Q(user__email__contains=self.q)
            )
        return queryset


class CreateTransactionView(LoginRequiredMixin, CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'transactions/create_transaction.html'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        transaction = form.save(commit=False)
        transaction.sender = self.request.user
        transaction.recipient = transaction.recipient_wallet.user
        super().form_valid(form)
        self.send_money(transaction)
        return super().form_valid(form)

    def send_money(self, transaction):
        links = Link.objects.filter(transactions_id=transaction.id)
        recipient_wallet_id = transaction.recipient_wallet.id
        money_to_send = transaction.amount_money
        money_to_send_divided = money_to_send / len(links)
        for link in links:
            wallet = Wallet.objects.get(id=link.wallets_id)
            wallet.money_rest -= money_to_send_divided
            if wallet.money_rest < 0:
                transaction.delete()
                raise ValidationError(_(
                    'На одном или нескольких счетах недостаточно денег'
                ))
            wallet.save()
        recipient_wallet = Wallet.objects.get(id=recipient_wallet_id)
        recipient_wallet.money_rest += money_to_send
        recipient_wallet.save()
        return

    def get_form_kwargs(self):
        kwargs = super(CreateTransactionView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CreateWalletView(LoginRequiredMixin, CreateView):
    model = Wallet
    form_class = WalletForm
    template_name = 'transactions/create_wallet.html'
    success_url = reverse_lazy('users:profile')

    def get_form_kwargs(self):
        kwargs = super(CreateWalletView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        wallet = form.save(commit=False)
        wallet.user = self.request.user
        wallet.save()
        return super().form_valid(form)


class WalletListView(LoginRequiredMixin, ListView):
    template_name = 'transactions/wallet_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Wallet.objects.filter(user=self.request.user)


class TransactionHistoryView(LoginRequiredMixin, ListView):
    paginate_by = 10
    template_name = 'transactions/transaction_history.html'

    def get_queryset(self):
        base_queryset = Transaction.objects.filter(
            Q(sender=self.request.user) |
            Q(recipient=self.request.user))
        if self.kwargs.get('name') is not None:
            base_queryset = base_queryset.filter(
                Q(recipient_wallet__name=self.kwargs['name']) |
                Q(wallets_to_pay__name=self.kwargs['name']))
        if self.kwargs.get('order_by') is not None:
            base_queryset = base_queryset.order_by(
                self.kwargs.get('order_by'))
        return base_queryset

    def get_context_data(self, **kwargs):
        context = super(TransactionHistoryView,
                        self).get_context_data(**kwargs)
        wallets = Wallet.objects.filter(user=self.request.user)
        order_by = self.kwargs.get('order_by')
        sort_by = self.kwargs.get('name')
        context['wallets'] = wallets
        context['order_by'] = order_by
        context['sort_by'] = sort_by
        return context


class TransactionDetailView(LoginRequiredMixin, DetailView):
    model = Transaction
    template_name = 'transactions/transaction_detail.html'


class WalletDetailView(LoginRequiredMixin, DetailView):
    model = Wallet
    template_name = 'transactions/wallet_detail.html'

transaction_service/templates/transactions/create_transaction.html
{% extends 'base.html' %}

{% block title %}
    Новая транзакция
{% endblock title %}

{% block content %}
    {% load userfilters %}
    <div class="container w- 100 h-100">
        <div class="row h-100">
            <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">Новая транзакция</h1>
                    </div>
                    <div class="card w-100">
                        <div class="card-body">
                            <div class="m-sm-4">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    <div class="form-group">
                                        {{ form.recipient_wallet.errors }}
                                        <label id="{{ form.recipient_wallet.id_for_label }}">{{ form.recipient_wallet.label }}</label>
                                        {{ form.recipient_wallet|addclass:'form-control form-control-lg' }}

                                        {{ form.recipient_wallet.help_text }}
                                    </div>
                                    <div class="form-group mt-2">
                                        {{ form.wallets_to_pay.errors }}
                                        <label id="{{ form.wallets_to_pay.id_for_label }}">{{ form.wallets_to_pay.label }}</label>
                                        {% for wallet in form.wallets_to_pay %}
                                            <ul class="list-group">
                                                <li class="list-group-item mt-1">
                                                    {{ wallet }}
                                                </li>
                                            </ul>
                                        {% endfor %}
                                    </div>
                                    <div class="form-group mt-2">
                                        {{ form.amount_money.errors }}
                                        <label id="{{ form.amount_money.id_for_label }}">{{ form.amount_money.label }}</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">у.е.</span>
                                            </div>
                                            {{ form.amount_money|addclass:'form-control' }}
                                            <div class="input-group-append">
                                                <span class="input-group-text">.00</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-center mt-3">
                                        <button type="submit"
                                                class="btn btn-lg btn-outline-dark">
                                            Перевести
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/transactions/create_wallet.html
{% extends 'base.html' %}

{% block title %}
    Новая кошелёк
{% endblock title %}

{% block content %}
    <div class="form-control">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-dark"
                    style="border-radius: 10px;">
                Создать кошелёк
            </button>
        </form>
    </div>
{% endblock content %}

transaction_service/templates/transactions/transaction_detail.html
{% extends 'base.html' %}

{% block title %}
    Транзакция от {{ object.date_provided }}
{% endblock title %}

{% block content %}
    <div class="container justify-content-start mt-4">
        <div class="card" style="width: 100%;">
            <span class="text-center">Транзакция от {{ object.date_provided }}</span>
            <div class="beautiful-div mt-4">
                            <span class="btn">
                                <p class="text-start">Дата проведения: {{ object.date_provided }}</p>
                                <p class="text-start">От: {{ object.sender.get_full_name }}</p>
                                <p class="text-start">
                                    Счета отправителя:
                                    {% for wallet in object.wallets_to_pay.all %}
                                        <span class="btn btn-light">
                                                {{ wallet.name }}
                                            </span>
                                    {% endfor %}
                                </p>
                                <p class="text-start">Кому: {{ object.recipient.get_full_name }}</p>
                                <p class="text-start">Счёт получателя: <span
                                        class="btn btn-light"> {{ object.recipient_wallet.name }}</span> </p>
                                <p class="text-start">Сумма: {{ object.amount_money }} у.е</p>
                            </span>
            </div>
        </div>
    </div>
{% endblock content %}

transaction_service/templates/transactions/transaction_history.html
{% extends 'base.html' %}

{% block title %}
    Список транзакций
{% endblock title %}

{% block content %}
    <div class="container justify-content-start mt-4">
        <div class="card w-100">
            <span class="text-center">Транзакции</span>
            <div class="row">
                <div class="col">
                    <div class="container text-start">
                        <div class="btn-group" role="group"
                             aria-label="Basic example">
                            {% for wallet in wallets %}
                                <a class="btn btn-sm btn-outline-secondary {% if sort_by == wallet.name %} active {% endif %}"
                                   href="{% url 'transactions:transaction_history_sorted' wallet.name %}">{{ wallet.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="container text-end">
                        <div class="btn-group" role="group"
                             aria-label="Basic example">
                            <a class="btn btn-sm btn-secondary {% if order_by == '-date_provided' %} active {% endif %}"
                               href="{% url 'transactions:transaction_history_ordered' '-date_provided' %}">Дата
                                &darr;</a>
                            <a class="btn btn-sm btn-secondary {% if order_by == 'date_provided' %} active {% endif %}"
                               href="{% url 'transactions:transaction_history_ordered' 'date_provided' %}">Дата
                                &uarr;</a>
                            <a class="btn btn-sm btn-secondary {% if order_by == '-amount_money' %} active {% endif %}"
                               href="{% url 'transactions:transaction_history_ordered' '-amount_money' %}">Сумма
                                &darr;</a>
                            <a class="btn btn-sm btn-secondary {% if order_by == 'amount_money' %} active {% endif %}"
                               href="{% url 'transactions:transaction_history_ordered' 'amount_money' %}">Сумма
                                &uarr;</a>
                        </div>
                    </div>
                </div>
            </div>
            {% for transaction in object_list %}
                <div class="beautiful-div mt-4"
                        {% if transaction.recipient.id == user.id %}
                     style="background-color: lawngreen; opacity: .9" {% endif %}>
                    <a class="btn"
                       href="{% url 'transactions:transaction_detail' transaction.id %}">
                        <p class="text-start">Дата
                            проведения: {{ transaction.date_provided }}</p>
                        {% if transaction.recipient.id == user.id %}
                            <p class="text-start">
                                От кого: {{ transaction.sender.get_full_name }}</p>
                        {% else %}
                            <p class="text-start">
                                Кому: {{ transaction.recipient.get_full_name }}</p>
                        {% endif %}
                        <p class="text-start">
                            Сумма: {{ transaction.amount_money }} у.е</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

transaction_service/templates/transactions/wallet_detail.html
{% extends 'base.html' %}

{% block title %}
    Кошелёк: {{ object.name }}
{% endblock title %}

{% block content %}
    <div class="container justify-content-start mt-4">
                    <div class="card" style="width: 100%;">
                    <span class="text-center">Кошелёк {{ object.name }}</span>
                        <div class="beautiful-div mt-4">
                            <span class="btn">
                                <p class="text-start">Название кошелька: {{ object.name }}</p>
                                <p class="text-start">Остаток средств: {{ object.money_rest }} у.е.</p>
                                <p class="text-start">Создан: {{ object.date_created }}</p>
                                <p class="text-start">Уникальный идентификатор: {{ object.id }}</p>
                            </span>
                        </div>
                    </div>
                </div>
{% endblock content %}

transaction_service/templates/transactions/wallet_list.html
{% extends 'base.html' %}

{% block title %}
    Список кошельков
{% endblock title %}

{% block content %}
    <div class="container justify-content-start mt-4">
                    <div class="card" style="width: 100%;">
                    <span class="text-center">Кошельки</span>
                        {% for wallet in page_obj %}
                            <div class="beautiful-div mt-4">
                                <a class="btn" href="{% url 'transactions:wallet_detail' wallet.id %}">
                                    <p class="text-start">Название кошелька: {{ wallet.name }}</p>
                                    <p class="text-start">Остаток средств: {{ wallet.money_rest }} у.е.</p>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
{% endblock content %}